version: '3.2'

services:
  python:
    container_name: django
    build:
      context: .
      dockerfile: 
        docker/prod/python/Dockerfile
      args:
        requirements: requirements/prod.txt
    environment:
      - SECRET_KEY=real-key-for-prod
      - DJANGO_SETTINGS_MODULE=framework.settings.production
    volumes:
      - ./src:/src
    ports:
      - "8002:8000"