version: '3.2'

services:
  python:
    container_name: django
    build:
      context: .
      dockerfile: 
        docker/dev/python/Dockerfile
      args:
        requirements: requirements/dev.txt
    environment:
      - DJANGO_SETTINGS_MODULE=framework.settings.development
    volumes:
      - ./src:/src
    ports:
      - "8001:8000"