version: '3.2'

services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: 
        docker/prod/python/Dockerfile
      args:
        requirements: requirements/prod.txt
    environment:
      - SECRET_KEY=real-key-for-prod
      - DJANGO_SETTINGS_MODULE=framework.settings.production
    volumes:
      - ./src:/src
    expose:
      - "8000"
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile:
        docker/prod/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - python